import { ExecutiveReport } from "@/lib/cfo/types";

/**
 * ============================================================
 * ARKENONE — COMPACT CFO CONTEXT
 * ============================================================
 *
 * This file converts the full ExecutiveReport into a compact
 * object specifically designed for "Ask Your CFO".
 *
 * IMPORTANT:
 *
 * We deliberately DO NOT send the entire report to OpenAI.
 *
 * The goal is:
 *
 * Full business data
 *        ↓
 * Local filtering
 *        ↓
 * Compact CFO context
 *        ↓
 * OpenAI
 *
 * This reduces unnecessary input tokens while preserving the
 * financial information required for executive reasoning.
 */

export interface AskCFOContext {
  company: {
    name: string;
    industry: string;
    businessModel: string;
    yearsInBusiness: number;
    annualRevenue: number;
    businessGoal: string;
    growthStage: string;
    riskAppetite: string;
  };

  financial: {
    revenue: number;
    expenses: number;
    profit: number;

    cash: number;
    cashFlow: number;

    grossMargin: number;
    netMargin: number;

    workingCapital: number;
    cashRunwayDays: number;
    monthlyBurnRate: number;

    outstandingReceivables: number;
    outstandingPayables: number;

    revenueGrowth: number;
    expenseGrowth: number;

    healthScore: number;
  };

  customers: {
    total: number;
    active: number;
    repeatCustomers: number;

    averageInvoiceValue: number;
    averagePaymentTime: number;

    customerConcentration: number;

    topCustomer: string;
    topCustomerRevenue: number;

    highestOutstandingCustomer: string;
    highestOutstandingAmount: number;
  };

  forecast: {
    next30Revenue: number;
    next30Expenses: number;
    next30Profit: number;

    expectedCashPosition: number;
    expectedGrowth: number;

    confidence: number;
  };

  workforce: {
    currentEmployees: number;
    financiallySustainableEmployees: number;
  };

  risks: string[];
}

/**
 * Convert unknown numeric values into safe finite numbers.
 */
function numberOrZero(value: unknown): number {
  const parsed = Number(value);

  return Number.isFinite(parsed)
    ? parsed
    : 0;
}

/**
 * Convert unknown strings into safe strings.
 *
 * We intentionally keep this conservative.
 */
function stringOrEmpty(value: unknown): string {
  return typeof value === "string"
    ? value.trim()
    : "";
}

/**
 * Remove empty risk entries.
 *
 * Risks are already generated by ArkenOne, so we do not create
 * new risks here.
 */
function sanitizeRisks(
  risks: unknown
): string[] {
  if (!Array.isArray(risks)) {
    return [];
  }

  return risks
    .filter(
      (risk): risk is string =>
        typeof risk === "string" &&
        risk.trim().length > 0
    )
    .map((risk) => risk.trim())
    .slice(0, 5);
}

/**
 * ============================================================
 * BUILD COMPACT ASK CFO CONTEXT
 * ============================================================
 */
export function buildAskCFOContext(
  report: ExecutiveReport
): AskCFOContext {
  return {
    /*
     * ========================================================
     * COMPANY
     * ========================================================
     */

    company: {
      name:
        stringOrEmpty(
          report.company.name
        ),

      industry:
        stringOrEmpty(
          report.company.industry
        ),

      businessModel:
        stringOrEmpty(
          report.company.businessModel
        ),

      yearsInBusiness:
        numberOrZero(
          report.company.yearsInBusiness
        ),

      annualRevenue:
        numberOrZero(
          report.company.annualRevenue
        ),

      businessGoal:
        stringOrEmpty(
          report.company.businessGoal
        ),

      growthStage:
        stringOrEmpty(
          report.company.growthStage
        ),

      riskAppetite:
        stringOrEmpty(
          report.company.riskAppetite
        ),
    },

    /*
     * ========================================================
     * FINANCIAL POSITION
     * ========================================================
     */

    financial: {
      revenue:
        numberOrZero(
          report.finance.revenue
        ),

      expenses:
        numberOrZero(
          report.finance.expenses
        ),

      profit:
        numberOrZero(
          report.finance.profit
        ),

      cash:
        numberOrZero(
          report.finance.cash
        ),

      cashFlow:
        numberOrZero(
          report.finance.cashFlow
        ),

      grossMargin:
        numberOrZero(
          report.finance.grossMargin
        ),

      netMargin:
        numberOrZero(
          report.finance.netMargin
        ),

      workingCapital:
        numberOrZero(
          report.finance.workingCapital
        ),

      cashRunwayDays:
        numberOrZero(
          report.finance.cashRunwayDays
        ),

      monthlyBurnRate:
        numberOrZero(
          report.finance.monthlyBurnRate
        ),

      outstandingReceivables:
        numberOrZero(
          report.finance
            .outstandingReceivables
        ),

      outstandingPayables:
        numberOrZero(
          report.finance
            .outstandingPayables
        ),

      revenueGrowth:
        numberOrZero(
          report.finance.revenueGrowth
        ),

      expenseGrowth:
        numberOrZero(
          report.finance.expenseGrowth
        ),

      healthScore:
        numberOrZero(
          report.finance.healthScore
        ),
    },

    /*
     * ========================================================
     * CUSTOMER ECONOMICS
     * ========================================================
     *
     * We exclude duplicate/raw fields that are unnecessary
     * for the conversational CFO.
     */

    customers: {
      total:
        numberOrZero(
          report.customers.total
        ),

      active:
        numberOrZero(
          report.customers.active
        ),

      repeatCustomers:
        numberOrZero(
          report.customers.repeatCustomers
        ),

      averageInvoiceValue:
        numberOrZero(
          report.customers
            .averageInvoiceValue
        ),

      averagePaymentTime:
        numberOrZero(
          report.customers
            .averagePaymentTime
        ),

      customerConcentration:
        numberOrZero(
          report.customers
            .customerConcentration
        ),

      topCustomer:
        stringOrEmpty(
          report.customers.topCustomer
        ),

      topCustomerRevenue:
        numberOrZero(
          report.customers
            .topCustomerRevenue
        ),

      highestOutstandingCustomer:
        stringOrEmpty(
          report.customers
            .highestOutstandingCustomer
        ),

      highestOutstandingAmount:
        numberOrZero(
          report.customers
            .highestOutstandingAmount
        ),
    },

    /*
     * ========================================================
     * FORECAST
     * ========================================================
     */

    forecast: {
      next30Revenue:
        numberOrZero(
          report.forecast
            .next30Revenue
        ),

      next30Expenses:
        numberOrZero(
          report.forecast
            .next30Expenses
        ),

      next30Profit:
        numberOrZero(
          report.forecast
            .next30Profit
        ),

      expectedCashPosition:
        numberOrZero(
          report.forecast
            .expectedCashPosition
        ),

      expectedGrowth:
        numberOrZero(
          report.forecast
            .expectedGrowth
        ),

      confidence:
        numberOrZero(
          report.forecast
            .confidence
        ),
    },

    /*
     * ========================================================
     * WORKFORCE
     * ========================================================
     *
     * The financially sustainable workforce is already
     * calculated by ArkenOne.
     *
     * We give GPT the baseline as evidence.
     */

    workforce: {
      currentEmployees:
        numberOrZero(
          report.workforce
            .currentEmployees
        ),

      financiallySustainableEmployees:
        numberOrZero(
          report
            .financiallySustainableEmployees
        ),
    },

    /*
     * ========================================================
     * RISKS
     * ========================================================
     *
     * Limit the number of risks to avoid unnecessarily large
     * prompts.
     */

    risks:
      sanitizeRisks(
        report.risks
      ),
  };
}