interface Props {
  title: string;
  periodStart: string;
  periodEnd: string;
}

export default function ReportHeader({
  title,
  periodStart,
  periodEnd,
}: Props) {
  return (
    <section className="rounded-[34px] border border-white/[0.08] bg-[#101214] px-10 py-10">

      <p className="text-[11px] uppercase tracking-[0.35em] text-[#D4AF37]">
        Executive Report
      </p>

      <div className="mt-5 flex items-start justify-between gap-10">

        <div>

          <h1 className="text-5xl font-semibold tracking-[-0.04em] text-white">
            {title}
          </h1>

          <p className="mt-4 text-lg text-zinc-500">
            {new Date(periodStart).toLocaleDateString("en-IN", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
            {" — "}
            {new Date(periodEnd).toLocaleDateString("en-IN", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
          </p>

          <p className="mt-2 text-sm text-zinc-600">
            Generated by ArkenOne AI CFO
          </p>

        </div>

        <div className="flex gap-3">

          <button className="rounded-2xl border border-white/10 bg-white/[0.03] px-5 py-3 text-sm text-white transition hover:bg-white/[0.05]">
            PDF
          </button>

          <button className="rounded-2xl border border-white/10 bg-white/[0.03] px-5 py-3 text-sm text-white transition hover:bg-white/[0.05]">
            Excel
          </button>

          <button className="rounded-2xl border border-white/10 bg-white/[0.03] px-5 py-3 text-sm text-white transition hover:bg-white/[0.05]">
            CSV
          </button>

          <button className="rounded-2xl border border-[#D4AF37]/20 bg-[#D4AF37]/10 px-5 py-3 text-sm font-medium text-[#D4AF37] transition hover:bg-[#D4AF37]/20">
            Print
          </button>

        </div>

      </div>

    </section>
  );
}